FROM docker.io/library/nginx:1
RUN echo '<h1 style="font-size: 100px;">v2.0</h1>' > /usr/share/nginx/html/index.html
RUN echo 'OK' > /usr/share/nginx/html/status
RUN sed 's/worker_processes  auto;/worker_processes  1;/g' -i /etc/nginx/nginx.conf
RUN grep worker -r /etc/nginx/nginx.conf /etc/nginx/conf.d/
