name: expressjs-example

on:
  push:
    branches:
      - master
#    paths:
#      - 'expressjs-example/*'

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          path: expressjs-example
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: jerolimov/docker/expressjs-example
          tag_with_ref: true
