name: postgres-example

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/postgres-example.yml'
      - 'postgres-example/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          path: postgres-example
          cache_froms: node:12-alpine
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: jerolimov/postgres-example
          tag_with_ref: true
      - uses: docker/build-push-action@v1
        with:
          path: postgres-example
          cache_froms: node:12-alpine
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: jerolimov/docker/postgres-example
          tag_with_ref: true
